services:
  mongo:
    image: mongo:latest
    container_name: gdash_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: gdash_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: gdash_worker
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672/
      - RABBITMQ_QUEUE=weather_data
      - API_URL=http://backend:3000/api

  collector:
    build: ./collector
    container_name: gdash_collector
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_QUEUE=weather_data

  backend:
    build: ./backend
    container_name: gdash_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - DATABASE_URL=mongodb://mongo:27017/gdash_db?authSource=admin

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: gdash_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data: